## Introduction to Python

### Python List

In [1]:
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

#### Subsetting List

In [2]:
fam[3]

1.68

In [3]:
fam[-1]

1.89

#### Slicing

In [4]:
fam[3:5]

[1.68, 'mom']

In [5]:
fam[:4]

['liz', 1.73, 'emma', 1.68]

In [6]:
fam[5:]

[1.71, 'dad', 1.89]

In [7]:
print(fam)
fam + ["me", 1.79]

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]

In [8]:
print(fam)
del(fam[2])
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


['liz', 1.73, 1.68, 'mom', 1.71, 'dad', 1.89]

### Functions

In [9]:
fam = [1.73, 1.68, 1.71, 1.89]
max(fam)   

1.89

In [10]:
round(1.68, 1)

1.7

#### Help (Open Documentation)

In [11]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



### Methods

In [12]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place); print(place_up)

# Print out the number of o's in place
print(place.count('o'))

poolhouse
POOLHOUSE
3


### NumPy

In [13]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out np_baseball
print(np_baseball)

print(type(np_baseball))

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


#### 2D NumPy Array

In [14]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [15]:
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 3th row of np_baseball
print(np_baseball[2, :])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]

# Print out height of 4th player
print(np_baseball[3, 0])

[210.   98.5]
188.0


#### NumPy: Basic Statistic

In [16]:
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: \n" + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: 
[[1.         0.95865738]
 [0.95865738 1.        ]]


#### Generate Data

In [17]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
np_city

array([[ 1.56, 59.19],
       [ 1.58, 59.92],
       [ 1.44, 70.14],
       ...,
       [ 1.63, 62.02],
       [ 1.48, 47.44],
       [ 1.8 , 53.18]])